language: python
python:
- "3.6"
node_js:
  - "node"
script:
  - "./util/travis"
deploy:
  skip_cleanup: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: chrisboyerdev@gmail.com
  password:
    secure: g9a/DUXWsyuBm1m2wMWvWM33ebdHWavAsddGbMVm9v1/fHhvxn1/wKW/MxOydyyTY5ULtpfKrbsgwbdkGbKtGZlr1CYlEd7lC6dtyjLdf3LEY/gFM1Si9JIQ52pzUqZxaHA71InZlu412xMRjzrwn7j2UURhzIkd3WgDoAzJBWNDy9ojCzHMr07GPcplPpf/VX/Nq9cGDMafaErcBSdaqwq1wClwRzCRJrTFCVRiBhe+QtYJ7FtKFHGsVXfH9pLoOAHR0eg0me7loEwDGvn+4o7mirx2dpfSqD4PvxKgtJM7BNFEBNfWA6n6AxsHUFT3wV/Ikof66yJn7xQlWnVLuK++k1BS9Jg1eYrc1/ir75JMbYUkllD6p0okGXqpnNG4AbTP+EF5caqBvMw/SPbOpDok2b8tIYWKcmIF6HzNfnWLMFsu1GYP1BR8CPRxcr6BLmErQH+gY/dOqBBdn2fJ9oNBwxg/mvArOBJO3s4e4cDBQzugnMrpaKWQ3OPnh2EgWIoQSQbjyo1tmWCCYCMCZ9ySqh9gZYQRjygf39+/S1M6BXUdyaFmCbJsDGUEPhoO7+DGAX8ywIiLNTrcieVt4uJ1AI5f9I/oqjNPWewi/tou1Za8CBuoOP2SPKpJ7fGz5SLZytLqUJgoVd6qyDkxszNsmymvqO8bZpKUhzVjFlA=
  organization: chrisboyerdev-org
  space: development
  on:
    repo: chiptopher/scalio
    branch: master